In [39]:
import pandas as pd
df = pd.read_csv('../data/raw/foodcom_reviews.csv')
df.info()
df.duplicated().sum()
df.isnull().sum()
data=pd.read_csv("../data/raw/foodcom_recipes.csv")
for i in data :
    if data[i].isnull().sum() > 0:
        data[i]=data[i].ffill()
data.duplicated().sum()
df.nunique().sort_values()
data.nunique().sort_values()
df.head(2).T
data.head(2).T
df.describe().T
data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 178265 entries, 0 to 178264
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 178265 non-null  int64
 1   i                  178265 non-null  int64
 2   name_tokens        178265 non-null  str
 3   ingredient_tokens  178265 non-null  str
 4   steps_tokens       178265 non-null  str
 5   techniques         178265 non-null  str
 6   calorie_level      178265 non-null  int64
 7   ingredient_ids     178265 non-null  str
dtypes: int64(3), str(5)
memory usage: 10.9 MB

RecipeId                      0
Name                          0
AuthorId                      0
AuthorName                    0
CookTime                      0
PrepTime                      0
TotalTime                     0
DatePublished                 0
Description                   0
Images                        0
RecipeCategory                0
Keywords                      0
RecipeIngredientQuantities    0
RecipeIngredientParts         0
AggregatedRating              0
ReviewCount                   0
Calories                      0
FatContent                    0
SaturatedFatContent           0
CholesterolContent            0
SodiumContent                 0
CarbohydrateContent           0
FiberContent                  0
SugarContent                  0
ProteinContent                0
RecipeServings                0
RecipeYield                   3
RecipeInstructions            0
dtype: int64

In [97]:
data

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,CookTime_minutes,PrepTime_minutes,TotalTime_minutes,PublishedYear,PublishedMonth
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09 21:46:00+00:00,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan...",0,0,0,1999,8
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29 13:12:00+00:00,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and...",0,0,0,1999,8
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05 19:52:00+00:00,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ...",0,0,0,1999,9
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03 14:54:00+00:00,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc...",0,0,0,1999,9
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19 06:19:00+00:00,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",...,17.7,4.3,4.0,4 kebabs,"c(""Mix everything together and bring to a boil...",0,0,0,1999,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522512,541379,Meg's Fresh Ginger Gingerbread,2002090414,rdsxc,PT35M,PT1H,PT1H35M,2020-12-22 15:27:00+00:00,Make and share this Meg's Fresh Ginger Gingerb...,character(0),...,22.8,3.9,8.0,1 8x8 cake pan,"c(""Preheat oven to 350&deg;F Grease an 8x8 cak...",0,0,0,2020,12
522513,541380,Roast Prime Rib au Poivre with Mixed Peppercorns,211566,Denver cooks,PT3H,PT30M,PT3H30M,2020-12-22 15:32:00+00:00,"White, black, green, and pink peppercorns add ...","""https://img.sndimg.com/food/image/upload/w_55...",...,0.1,117.0,8.0,1 Roast,"c(""Position rack in center of oven and preheat...",0,0,0,2020,12
522514,541381,Kirshwasser Ice Cream,2001131545,Jonathan F.,PT3H,PT1H,PT4H,2020-12-22 15:33:00+00:00,Make and share this Kirshwasser Ice Cream reci...,character(0),...,17.3,12.8,6.0,1 Roast,"c(""heat half and half and heavy cream to a sim...",0,0,0,2020,12
522515,541382,Quick & Easy Asian Cucumber Salmon Rolls,2001004241,CLUBFOODY,PT3H,PT15M,PT15M,2020-12-22 22:11:00+00:00,"Extremely quick and easy to make, these are gr...","""https://img.sndimg.com/food/image/upload/w_55...",...,0.1,2.4,6.0,20 rolls,"c(""In a small bowl, combine mayo and wasabi pa...",0,0,0,2020,12
522516,541383,Spicy Baked Scotch Eggs,188099,Chef LauraMD,PT25M,PT15M,PT40M,2020-12-22 22:12:00+00:00,"Great way to have hard boiled eggs and crispy,...",character(0),...,6.7,76.4,6.0,20 rolls,"c(""Mix sausage, panko, egg yolk and Wocestersh...",0,0,0,2020,12

Main transformation start from here

In [40]:
# convert time to minute
import re 
def time_to_minutes(time):
    match=re.match(r'PT(?:(\d+)H)?:(\d+)M?',str(time))
    
    if not match:
        return 0
    hours=int(match.group(1)or 0)
    minutes=int(match.group(2) or 0 )
    return hours *60 + minutes

In [41]:
data['CookTime_minutes']=data['CookTime'].apply(time_to_minutes)
data['PrepTime_minutes']=data['PrepTime'].apply(time_to_minutes)
data['TotalTime_minutes']=data['TotalTime'].apply(time_to_minutes)

In [44]:
data[['CookTime','CookTime_minutes',"PrepTime",'PrepTime_minutes','TotalTime','TotalTime_minutes']].head()

,CookTime,CookTime_minutes,PrepTime,PrepTime_minutes,TotalTime,TotalTime_minutes
0,PT24H,0,PT45M,0,PT24H45M,0
1,PT25M,0,PT4H,0,PT4H25M,0
2,PT5M,0,PT30M,0,PT35M,0
3,PT20M,0,PT24H,0,PT24H20M,0
4,PT30M,0,PT20M,0,PT50M,0

datapublished to datetime

In [45]:
data['DatePublished']=pd.to_datetime(data['DatePublished'],errors='coerce')
data['DatePublished'].isnull().sum()

In [50]:
data['PublishedYear'] = data['DatePublished'].dt.year
data['PublishedMonth']=data['DatePublished'].dt.month

we'll parse Keywords , RecipeIngredientsParts . and RecipeIngredientsQunatities into porper python lists

In [65]:
data.columns.tolist()

['RecipeId',
 'Name',
 'AuthorId',
 'AuthorName',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'DatePublished',
 'Description',
 'Images',
 'RecipeCategory',
 'Keywords',
 'RecipeIngredientQuantities',
 'RecipeIngredientParts',
 'AggregatedRating',
 'ReviewCount',
 'Calories',
 'FatContent',
 'SaturatedFatContent',
 'CholesterolContent',
 'SodiumContent',
 'CarbohydrateContent',
 'FiberContent',
 'SugarContent',
 'ProteinContent',
 'RecipeServings',
 'RecipeYield',
 'RecipeInstructions',
 'CookTime_minutes',
 'PrepTime_minutes',
 'TotalTime_minutes',
 'PublishedYear',
 'PublishedMonth']

In [87]:
import ast
def parse_list(value):
    try:
        value = str(value).strip()

        if value.startswith("c(") and value.endswith(")"):
            value = "[" + value[2:-1] + "]"

        result = ast.literal_eval(value)

        if isinstance(result, (list, tuple)):
            return list(result)

        if isinstance(result, str):
            return [result]

        return []

    except (ValueError, SyntaxError, TypeError):
        return []
list_cols = [
    "Keywords",
    "RecipeIngredientParts",
    "RecipeIngredientQuantities"
]

for col in list_cols:
    data[col] = data[col].apply(parse_list)

In [95]:
type(data["Keywords"].iloc[0])
# data["Keywords"]

list

In [93]:
data[["Keywords", "RecipeIngredientParts",
      "RecipeIngredientQuantities"]]
print(repr(data["Keywords"].iloc[0]))
print(repr(data["RecipeIngredientParts"].iloc[0]))

[]
[]

In [96]:
print(repr(data["Keywords"].iloc[38]))
print(repr(data["RecipeIngredientParts"].iloc[38]))
print(repr(data["RecipeIngredientQuantities"].iloc[38]))

['<', '3', '0', 'm', 'i', 'n', 's']
[]
[]

ingredient normalization. This is important because "Chicken Breast" and "chicken breast " should become the same ingredient.

In [83]:
def clean_ingredients(ingredients):
    return[
        str(item).strip().lower()
        for item in ingredients
        if str(item).strip()
    ]
data['RecipeIngredientParts']=data['RecipeIngredientParts'].apply(clean_ingredients)

In [84]:
data['RecipeIngredientParts'].head(3)

0    []
1    []
2    []
Name: RecipeIngredientParts, dtype: object

In [85]:
data["Keywords"]=data["Keywords"].apply(clean_ingredients)

In [86]:
data[['Name','Keywords','RecipeIngredientParts']].head(3)

                                Name Keywords RecipeIngredientParts
0  Low-Fat Berry Blue Frozen Dessert       []                    []
1                            Biryani       []                    []
2                      Best Lemonade       []                    []